# Generated by Django 3.2.5 on 2023-03-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locationadress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationdata', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Locationdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationlink', models.TextField()),
                ('addressdata', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mappin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapurl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mapsdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maplink', models.TextField()),
                ('mapaddress', models.TextField()),
                ('mapcity', models.TextField()),
                ('mapstate', models.TextField()),
                ('mapcountry', models.TextField()),
                ('mapzip', models.TextField()),
            ],
        ),
    ]
